[build]
  command = "npm ci && NODE_OPTIONS='--no-warnings' npm run build"
  publish = "dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . || exit 0"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "9.8.1"
  # Prevent automatic CSS framework detection
  NETLIFY_SKIP_EDGE_HANDLERS = "true"
  # Disable PostCSS processing
  DISABLE_POSTCSS = "true"
  # Skip CSS framework detection
  SKIP_CSS_FRAMEWORKS = "true"
  # Disable automatic dependency detection
  NETLIFY_SKIP_DEPENDENCY_INSTALLER = "true"