[build]
  command = "npm ci --production=false && npm run build"
  publish = "dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF"

[build.environment]
  NODE_VERSION = "18"
  YARN_VERSION = "1.22.19"
  RUBY_VERSION = "2.7.2"