[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "9.8.1"
  # Prevent automatic CSS framework detection
  NETLIFY_SKIP_EDGE_HANDLERS = "true"