[build]
  command = "npm install --only=prod --no-optional && npm install --only=dev --no-optional && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_AUDIT = "false"
  NPM_CONFIG_FUND = "false"
  DISABLE_ESLINT_PLUGIN = "true"
  SKIP_PREFLIGHT_CHECK = "true"